//
//  DeveloperPreview.swift
//  AirBnbTourior
//
//  Created by 王佩豪 on 2024/4/7.
//

import Foundation

class DeveloperPreview{
    
    static let shared = DeveloperPreview()
    
    var listing:[Listing] = [
        .init(
          id: NSUUID().uuidString,
          title: "Miami Villa",
          ownerId: NSUUID().uuidString,
          ownerName: "John Smith",
          ownerImageUrl: "lucas",
          numOfGuests: 3,
          numOfBedrooms: 7,
          numOfBethrooms: 1,
          numOfBeds: 3,
          pricePerNight: 399,
          latitude: 34.532,
          longitude: 192.168,
          imageUrls: ["hotel-1","hotel-2","hotel-3","hotel-4"],
          address: "TJISE",
          city: "los Angeles",
          state: "Steate",
          rating: 4.82,
          features: [.superHost],
          things: [.kitchen,.pool,.tv,.wifi],
          type: [.townHouse]),
        .init(
          id: NSUUID().uuidString,
          title: "Beijign Villa",
          ownerId: NSUUID().uuidString,
          ownerName: "John Smith",
          ownerImageUrl: "lucas",
          numOfGuests: 3,
          numOfBedrooms: 10,
          numOfBethrooms: 1,
          numOfBeds: 3,
          pricePerNight: 399,
          latitude: 34.532,
          longitude: 192.168,
          imageUrls: ["hotel-3","hotel-4","hotel-6","hotel-7"],
          address: "TJISE",
          city: "LA",
          state: "Steate",
          rating: 3.456,
          features: [.selfCheckin,.superHost],
          things: [.kitchen,.pool,.tv,.wifi],
          type: [.townHouse]),
        .init(
          id: NSUUID().uuidString,
          title: "Shanghai Villa",
          ownerId: NSUUID().uuidString,
          ownerName: "John Smith",
          ownerImageUrl: "lucas",
          numOfGuests: 3,
          numOfBedrooms: 2,
          numOfBethrooms: 1,
          numOfBeds: 3,
          pricePerNight: 399,
          latitude: 34.532,
          longitude: 192.168,
          imageUrls: ["hotel-4","hotel-5","hotel-6","hotel-7"],
          address: "TJISE",
          city: "DaTong",
          state: "Steate",
          rating: 3.23,
          features: [.selfCheckin,.superHost],
          things: [.kitchen,.pool,.tv,.wifi,.balcony],
          type: [.townHouse]),
        .init(
          id: NSUUID().uuidString,
          title: "Hangzhou Villa",
          ownerId: NSUUID().uuidString,
          ownerName: "John Smith",
          ownerImageUrl: "lucas",
          numOfGuests: 3,
          numOfBedrooms: 20,
          numOfBethrooms: 1,
          numOfBeds: 3,
          pricePerNight: 399,
          latitude: 34.532,
          longitude: 192.168,
          imageUrls: ["hotel-6","hotel-7","hotel-3","hotel-4"],
          address: "TJISE",
          city: "Beijing",
          state: "Steate",
          rating: 4.12,
          features: [.selfCheckin,.superHost],
          things: [.kitchen,.pool,.tv,.wifi],
          type: [.townHouse]),
        .init(
          id: NSUUID().uuidString,
          title: "World Villa",
          ownerId: NSUUID().uuidString,
          ownerName: "John Smith",
          ownerImageUrl: "lucas",
          numOfGuests: 3,
          numOfBedrooms: 20,
          numOfBethrooms: 1,
          numOfBeds: 3,
          pricePerNight: 399,
          latitude: 34.532,
          longitude: 192.168,
          imageUrls: ["hotel-1","hotel-2","hotel-6","hotel-4"],
          address: "TJISE",
          city: "Beijing",
          state: "Steate",
          rating: 4.99,
          features: [.selfCheckin,.superHost],
          things: [.kitchen,.pool,.tv,.wifi],
          type: [.townHouse]),
        .init(
          id: NSUUID().uuidString,
          title: "Hello Villa",
          ownerId: NSUUID().uuidString,
          ownerName: "John Smith",
          ownerImageUrl: "lucas",
          numOfGuests: 3,
          numOfBedrooms: 20,
          numOfBethrooms: 1,
          numOfBeds: 3,
          pricePerNight: 399,
          latitude: 34.532,
          longitude: 192.168,
          imageUrls: ["hotel-6","hotel-7","hotel-3","hotel-4"],
          address: "TJISE",
          city: "LA",
          state: "State",
          rating: 4.20,
          features: [.selfCheckin,.superHost],
          things: [.kitchen,.pool,.wifi],
          type: [.townHouse])
    ]
}
